### ISSUE TITLE
What is the simplest possible way of testing Riot.js apps?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-riot#1]
Taks: investigate/list _**all**_ the options for testing Riot.js apps. Determine which one is the _simplest_!

@besarthoxhaj @NataliaLKB @Danwhy @jrans

**Comment by besarthoxhaj** [comment]
Roger!

**Comment by samhstn** [comment]
@nelsonic I think the simplest way of testing riot _components_ would be running checks on the string output from the riot.render method, I'm not really a fan of this though.

I think the way I would like to test my application would be by using karma (potentially with [karma-riot](https://www.npmjs.com/package/karma-riot))

**Comment by nelsonic** [comment]
@shouston3 `karma-riot` looks _v. interesting_ especially as @tipiirai is working on it...
have you seen: https://github.com/dwyl/learn-nightwatch ?
if you need "_real world_" examples, see: 
https://github.com/TheScienceMuseum/collectionsonline/tree/master/test/client
These tests are from a _user_ perspective (_in real browsers_) ...

**Comment by samhstn** [comment]
@nelsonic thanks for pointing me to nightwatch, I think we're going to use it in my current project over karma (we couldn't manage the end to end tests we were looking for). The only issue I'm having with nightwatch that it is a bit slow...

**Comment by nelsonic** [comment]
@shouston3 yeah, agreed, the _only_ thing holding back Nightwatch is `selenium`, which is _abominably_ slow ... sadly, I don't see a "_solution_" to this on the horizon... 😞 

I'm _always_ open to suggestions...

**Comment by samhstn** [comment]
[karma-riot](https://github.com/riot/karma-riot) is no longer being maintained by @tipiirai and is now part of the riot organisation.

I have been [playing around with it](https://github.com/shouston3/riot-karma) and find that it's really nice to use

**Comment by nelsonic** [comment]
@shouston3 what makes you think/say that `karma-riot` is no longer maintained? 🤔 
(_my guide is super-stale issue/bugs and ignored open PRs... which the repo does not `appear` to have..._)
you _could_ contact @cognitom and ask to be added as a colab/co-maintainer if there are specific improvements you want to make, meanwhile I'd ❤️  to hear more about your experiments, and I'm pretty _sure_ @jackcarlisle & @jrans will be too for their Client-project which is a full-stack Riot app! 😮

**Comment by samhstn** [comment]
Sorry I don't think my last post was clear, I meant that the karma-riot repo is now being maintained by the maintainers of riot

**Comment by nelsonic** [comment]
@shouston3 nah, your comment was clear.
I just read it with "_tired eyes/brain_" so I didn't "_get_" it. 😉 
That's really cool/exciting so it's "_officially_" supported! 🎉

**Comment by cognitom** [comment]
Hi. we're using karma-riot by ourself, too 😸 

BTW, I think karma-riot is a good option for simple tags without dependencies, but if tags have dependencies (`import somthing from 'outside'`), karma-rollup could be another option.
See more detail here:
https://github.com/riot/riot/blob/v3.0.1/test/karma.conf.js#L62-L78
