### ISSUE TITLE
SkillShare Master Riot Course

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-riot#10]
While searching on YouTube for Riot.js Videos I came across this "**_Why Riot**_"? video

[![why-riot](https://cloud.githubusercontent.com/assets/194400/17972554/072fb698-6ad7-11e6-90a7-80b65d685a07.png)](https://youtu.be/pnoXL667sro)

I checked it out and it looks _really_ focussed. 

https://www.skillshare.com/classes/technology/Master-Riot-Learn-Riotjs-from-Scratch/1062917834
![skillshare-riotjs-promo](https://cloud.githubusercontent.com/assets/194400/17970138/2c0019ae-6acd-11e6-98d7-c750cf20725a.png)

https://www.udemy.com/master-riot/?couponCode=RIOT_SPECIAL
<img width="910" alt="udemy-riot js-course" src="https://cloud.githubusercontent.com/assets/194400/17840121/2ecb241a-67f5-11e6-9aa8-c1cd46dc27d8.png">

**Comment by nelsonic** [comment]
I signed up to SkillShare so we can do this course, message me for details.

**Comment by ruchidhana** [comment]
i really like to learn riot ... may i have a coupon for this course for totally free?

**Comment by nelsonic** [comment]
@ruchidhana, since we opened this 2 years ago, we have cancelled our SkillShare subscription because nobody on our team was using it, sorry. 
Riot.js is _good_, however, We _highly_ recommend you consider learning/using Elm instead: https://github.com/dwyl/learn-elm
