### ISSUE TITLE
Add section on simple set up of a riot project?

### ISSUE THREAD

**Issue by iteles** [dwyl/learn-riot#12]
I find that understanding how to set up a project is usually a nice introduction to the various things I'll need to understand for the thing I'm trying to learn.

Shall I have a go at including a section on this here to see if it makes sense or shall we leave this repo just as a compilation of external resources?

**Comment by nelsonic** [comment]
Really _stoked_ you're going to do this. 👍

**Comment by LasaleFamine** [comment]
Is one thing I couldn't find easily when I started to learn Riot, so I think could be very helpful!

**Comment by nelsonic** [comment]
@LasaleFamine by the end of this month our riot learning resources will be at a _whole_ other level! 😉

**Comment by iteles** [comment]
Riot is no longer part of our https://github.com/dwyl/technology-stack/

More info here: https://github.com/riot/riot
