### ISSUE TITLE
Server-Side Rendering Example?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-riot#2]
Can we put together a server-side rendering example that works...?
I tried: https://github.com/docdis/learn-riot/tree/04f0cad566d79da50407b05a7871e41399f54fa4/hello
but cannot get it to render out the variable on the server.

Posted this issue on the Riot.js github: https://github.com/riot/riot/issues/998
And getting some insight from: https://github.com/ListnPlay/riot-isomorphic/issues/8 where @Avnerus is _patiently_ answering my (_frankly_) "_noob_" questions ...
But I've tried to go through the riot.js source and not found _how_ the server-side example on the riot.js website is _meant_ to work...

 riot.js homepage: https://muut.com/riotjs/guide/#server-side
is confusing to beginners. 
<img width="691" alt="riot js-server-side-rendering-instructions-non-existent" src="https://cloud.githubusercontent.com/assets/194400/8751923/51134cc0-2ca8-11e5-95c0-c642b97ef375.png">

@besarthoxhaj @Danwhy @jrans + everyone else interested in helping move this forward, please investigate! thanks! :+1:

**Comment by besarthoxhaj** [comment]
Will do!!

**Comment by nelsonic** [comment]
@besarthoxhaj + @jrans want to pair on this today/now?
