### ISSUE TITLE
Compare Riot to other ways of building components?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/learn-riot#6]
Should we _bother_ adding a section comparing Riot to other ways of building components?

http://riotjs.com/compare/ ... 

Or are people going to what is fashionable irrespective of what is _logically better for people using the end product_...? 

![react-is-the-new-smoking](https://cloud.githubusercontent.com/assets/194400/10955754/12487ab8-834e-11e5-9c94-416d41ffa153.jpg)

**Comment by iteles** [comment]
I think it makes sense to explain our position on the subject concisely, but no need to go into detailed comparisons _here_. Good to point people to the link you have above :+1:
